#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ dko@139.162.62.175:/var/www/roasitas.com/
echo "Deployment complete"