# Generated by Django 3.0.1 on 2020-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
