# Generated by Django 3.0.1 on 2020-01-08 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200108_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='family',
            new_name='family_id',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients_id',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='unit',
            new_name='unit_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='images/dish'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='food.Recipe'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='MeasurementQty',
        ),
    ]
