# Generated by Django 3.0.1 on 2020-01-09 06:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200109_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredients_id',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_unit', to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='recipe_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_unit', to='food.RecipeIngredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredients',
            field=models.ManyToManyField(related_name='RecipeIngredient', through='food.MeasurementUnit', to='food.Ingredient'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('l', 'l'), ('g', 'g'), ('kg', 'kg')], default='g', max_length=10),
        ),
    ]
