# Generated by Django 3.0.1 on 2020-01-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200109_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='food.Category'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='steps',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.RecipeIngredient'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
