# Generated by Django 2.2.7 on 2019-12-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmember',
            name='subscribed',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
