# Generated by Django 2.2.7 on 2019-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20191229_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmember',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='emailmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
