# Generated by Django 3.0.1 on 2020-02-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200211_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
